/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import junit.framework.Assert;
import static org.junit.Assert.*;
import java.io.*;
import java.util.ArrayList;
import java.util.Collections;

public class AppTest {

    public App tester;

    // private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();

    @Before public void initObject() {
        tester = new App();
       //  System.setOut(new PrintStream(outContent));
    }

    @Test public void decreaseByCoin_50() {
      assertEquals("case for 50", 0, tester.decreaseByACoin(50, 50));
    }
    @Test public void decreaseByCoin_40() {
      assertEquals("case for 40", 0, tester.decreaseByACoin(40, 20));
    }
    @Test public void decreaseByCoin_30() {
      assertEquals("case for 30", 10, tester.decreaseByACoin(30, 20));
    }
    @Test public void decreaseByCoin_14() {
      assertEquals("case for 14", 4, tester.decreaseByACoin(14, 5));
    }
    @Test public void returnsArrayOfCoins50() {
        ArrayList<Integer> afterOperation = tester.coinChanger(50);
        ArrayList<Integer> expectedOutput = new ArrayList<>();
        Collections.addAll(expectedOutput, 50);
        assertTrue(afterOperation.equals(expectedOutput));
    }
    @Test public void returnsArrayOfCoins20() {
        ArrayList<Integer> aftOpTwo = tester.coinChanger(20);
        ArrayList<Integer> expectedOutputTwo = new ArrayList<>();
        Collections.addAll(expectedOutputTwo, 20);
        assertTrue(aftOpTwo.equals(expectedOutputTwo));
    }

    // @Test public void  printsResultForOneCoin() {
    //     // tester.resultPrinter(1);
    //     ByteArrayOutputStream os = new ByteArrayOutputStream();
    //     PrintStream ps = new PrintStream(os);
    //     System.setOut(ps);
    //     System.out.print("You will get 1 coin");
    //     assertEquals("You will get 1 coin", os.toString());
    // }
    // @Test public void printsResultForManyCoins() {
    //     // tester.resultPrinter(2);
    //     OutputStream os = new ByteArrayOutputStream();
    //     PrintStream ps = new PrintStream(os);
    //     System.setOut(ps);
    //     System.out.print("You will get 2 coins");
    //     assertEquals("You will get 2 coins", os.toString());
    // }

    // @Test public void terminalOutput() {
    //     System.out.print("hello");
    //     assertEquals("hello", outContent.toString());
    // }

    // @After
    //   public void restoreStreams() {
    //     System.setOut(System.out);
    //     System.setErr(System.err);
    //  }
}
