/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void returnsNumberOfCoins50() {
        App classUnderTest = new App();
        assertEquals("case for 50", 1, classUnderTest.coinChanger(50));
    }
    @Test public void returnsNumberOfCoins50_20_10() {
        App classUnderTest = new App();
        assertEquals("case for 90", 3, classUnderTest.coinChanger(90));
        assertEquals("case for 70", 2, classUnderTest.coinChanger(70));
        assertEquals("case for 40", 2, classUnderTest.coinChanger(40));
    }
    @Test public void returnsNumberOfCoins50_20_10_5() {
        App classUnderTest = new App();
        assertEquals("case for 95", 4, classUnderTest.coinChanger(95));
    }
    @Test public void returnsNumberOfCoins50_20_10_5_2() {
        App classUnderTest = new App();
        assertEquals("case for 97", 5, classUnderTest.coinChanger(97));
    }
    @Test public void returnsNumberOfCoins50_20_10_5_2_1() {
        App classUnderTest = new App();
        assertEquals("case for 98", 6, classUnderTest.coinChanger(98));
    }
}
